### ISSUE TITLE
brainstorm/talk through handling of reg not found

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#286]
Some users think they're done with the process when they get the "not registered" page and hand the tablet back

**Comment by karpet** [comment]
Sounds like a language / layout change is in order.

Current page:

![screen shot 2018-08-23 at 9 41 58 am](https://user-images.githubusercontent.com/99722/44532485-d0148880-a6b8-11e8-989a-9d99b290ed03.png)

Maybe the call to action button/language needs more positive assertion? Instead of "sorry..." maybe:
> You are not registered to vote. Register now!

**Comment by katherinepdavis** [comment]
Yes. That's great. So the header text is "You are not registered to vote." and button text is "Register now!"?

Then text underneath stays the same.

**Comment by karpet** [comment]
#294
