### ISSUE TITLE
Switch out AV form

### ISSUE THREAD

**Issue by katherinepdavis** [BlueprintKansas/ksvotes.org#412]
They updated the form to add the disability language.

[https://app.zenhub.com/files/133370577/3d4cdfb4-056c-49e6-a553-c7813967cbfc/download](https://app.zenhub.com/files/133370577/3d4cdfb4-056c-49e6-a553-c7813967cbfc/download)

**Comment by katherinepdavis** [comment]
This has become high priority because the old form has the former SOS name on it. New file is here: https://www.kssos.org/forms/elections/AV1.pdf

**Comment by karpet** [comment]
I have put a copy here https://ksvotes-v2.s3.amazonaws.com/AV1M.png with the following changes:

* removed the "Print" or "Reset" controls from the upper right (since those should only appear on the actionable PDF version)
* limited the form to the first page (without the 2nd page of all county clerk contacts)

@katherinepdavis can you confirm the .png looks correct?  then we can get started on the coordinates.

**Comment by karpet** [comment]
Same for permanent AV form: https://ksvotes-v2.s3.amazonaws.com/AV2.png

**Comment by karpet** [comment]
in production for week+
