### ISSUE TITLE
Query result returns wrong data with multiple matches

### ISSUE THREAD

**Issue by martialhax** [BlueprintKansas/ksvotes.org#574]
There is an issue with the SQL query on the live site.
When a user with the same first-last name and DOB enters their data along with zipcode etc. If multiple matches are found the site populates the first match's personal details on subsequent displayed forms. 

The database being used holds middle initial or name as well as zip. Zip is even being requested on the intial intake form. An additional check would fix this issue. If multiple rows are returned, you can even hold in a temporary data structure and do the additional check before using/displaying. There are other ways to fix as well.

**Comment by martialhax** [comment]
Requesting update I see this is monitored. Thanks.

**Comment by karpet** [comment]
Thanks for reporting this.

There are three distinct pieces to this bug.

1. The ksvotes site does not issue any SQL queries to match voter data. We use screen scraping of the https://myvoteinfo.voteks.org/VoterView site, which only allows for First/Last/DOB fields.
2. The ksvotes code takes the "first" match if there are multiple, without doing any further filtering based on the available data (ZIP code). That bug should be fixed by #576.
3. If there are still multiple matches found after the ZIP filter is applied, ksvotes should offer a selection option to the user. That is captured in #577.

**Comment by martialhax** [comment]
Thanks the zip check would fix this in the case I am aware of. The likelihood of a tertiary check needed is possible but probability is much lower.

**Comment by karpet** [comment]
Thanks @martialhax -- the fix is deployed.

**Comment by martialhax** [comment]
Thanks @karpet fix confirmed.
